config/routes.rb
Talent::Application.routes.draw do

  get "orders/index"

  get "orders/show"

  get "orders/create"

  get "orders/edit"

  get "orders/update"

  get "orders/destroy"

  resources :artworks
  resources :sellables
  match 'artworks/by/:artist_id' => "artworks#index", as: "artist_artworks"
  match 'artworks/by/:artist_id/edit' => "artworks#edit_all", as: "edit_artist_artworks"
  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :parks

  resources :projects, :only=>[:index, :show, :new,:create, :edit,:update, :destroy]
  match 'project/:id/apply'=>"projects#apply", :as=>'project_apply'
  match 'project_membership/:id/approve'=>"projects#approve",:as=>'project_approve'
  match 'project_membership/:id/decline'=>"projects#decline",:as=>'project_decline'
  match 'project_membership/:id/quit'=>"projects#quit", :as=>'project_quit'
  match 'project/overview'=>'projects#overview', :as=>'project_overview'
  match 'project/search'=>'projects#search', :via=>[:post,:put],:as=>"project_search"
  get "project/search(/:search_id)"=>'projects#index', :as=>"projects_list"

  resources :job_posts
  match "job_posts/:id/match"=>"job_posts#matching_talent",:as=>'job_post_matching_talent'
  resources :organization_profiles

  resources :tech_posts
  match 'tech_searches/default'=>'tech_searches#show',:as=>'default_tech_post'
  resources :tech_searches


  devise_for :users, :controllers => {:registrations => "registrations", :invitations => 'invitations'}

  resources :users
  resources :ind_users, path: "artists"
  resources :org_users, path: "buyers"
  resources :shouts
  match 'weibo(/:type)'=>'shouts#index', :as=>'myshouts'

  post 'send_message'=>"messages#create", :as=>'send_message'
  post 'send_job_application'=>"job_applications#create", :as=>'send_job_application'
  get 'cancel_job_application/:id'=>'job_applications#destroy',:as=>"cancel_job_application"
  post 'send_tech_application'=>"tech_applications#create", :as=>'send_tech_application'
  get 'cancel_tech_application/:id'=>'tech_applications#destroy',:as=>"cancel_tech_application"

  match 'overview' => 'ind_users#overview', :as=>'ind_user_overview'
  match 'job_searches/default'=>'job_searches#show',:as=>'default_jobs'
  match 'talent_searches/default'=>'talent_searches#show',:as=>'default_talent'
  match 'company_searches/default'=>'company_searches#show',:as=>'default_companies'
  match 'park_searches/default'=>'park_searches#show', :as=>'default_parks'
  resources :job_searches
  resources :company_searches
  resources :talent_searches
  resources :park_searches
  match 'ind_users/:id/new/:info'=>'ind_users#new',:as=>'ind_user_new'
  match 'ind_users/:id/edit/:info'=>'ind_users#edit',:as=>'ind_user_edit'
  match 'ind_users/:id/profile'=>'ind_users#profile',:as=>'ind_user_profile'
  match 'ind_users/:id/weibo'=>'ind_users#shouts',:as=>'ind_user_shouts'


  match 'bookmarked/ind/users'=>'ind_users#bookmarked_users', :as=>"bookmarked_users"
  match 'bookmarked/org/users'=>'org_users#bookmarked_users', :as=>"bookmarked_users_for_companies"
  match 'bookmarked/companies'=>'ind_users#bookmarked_companies', :as=>"bookmarked_companies"
  match 'bookmarked/jobs'=>'ind_users#bookmarked_jobs', :as=>"bookmarked_jobs"
  match 'bookmarked/projects'=>'ind_users#bookmarked_projects', :as=>"bookmarked_projects"


  match 'org_users/:id/new/:info'=>'org_users#new',:as=>'org_user_new'
  match 'org_users/:id/edit/:info'=>'org_users#edit',:as=>'org_user_edit'
  match 'org_users/:id/profile'=>'org_users#profile',:as=>'org_user_profile'
  match 'org_users/:id/weibo'=>'org_users#shouts',:as=>'org_user_shouts'
  match 'projects/:id/weibo'=>'projects#shouts',:as=>'project_shouts'

  match 'users/:id/update/account'=>"users#update_email_or_password",:as=>'user_update_email_or_password'
  match 'users/:id/new/:info'=>'users#new',:as=>'user_new'
  match 'users/:id/edit/:info'=>'users#edit',:as=>'user_edit'
  match 'users/:id/profile'=>'users#profile',:as=>'user_profile'

  match 'org_users/:id/jobs_posts'=>'org_users#job_posts',:as=>'org_user_job_posts'
  match 'ind_users/:id/jobs_posts'=>'ind_users#job_posts',:as=>'ind_user_job_posts'

  match 'skills/list'=>'skills#list',:as=>'skills_list'

  match 'bookmark/:type/:id'=>'bookmarks#bookmark', :as=>'toggle_bookmark'

  get "referralbonus" => 'pages#referralbonus', as: "pages_referralbonus"
  get "company" => 'pages#company'
  get "services" => 'pages#services'
  get "team" => 'pages#team'
  get "contact" => 'pages#contact'
  get "jobs" => 'pages#jobs'


  root :to => 'artworks#index'

  match 'job_posts/:id/toggle_promo'=>"job_posts#toggle_promo", as: 'toggle_promo'
  match "/artists_entrance" => "artworks#index", defaults: { locale: :en }
  match "/buyer_entrance" => "artworks#index", defaults: { locale: :ch }
  resources :orders
  match "/cancel_oder/:id" => "orders#cancel", as: "cancel_order"

  namespace :admin do
    resources :artworks
    resources :orders
    resources :artists
    resources :org_users
  end

  namespace :manage do
    resources :artworks
  end

  match "artworks/page/:page" => "artworks#index"

  match "/error" => "pages#error"
  match "*path" => "artworks#index"
end

app/models/shout.rb
class Shout
  include Mongoid::Document
  include Mongoid::Timestamps
  scope :top_level, where(:shout_id=>nil)
  default_scope all(sort: [[ :created_at, :desc ]])
  field :message
  field :message_with_link
  belongs_to :project
  belongs_to :user

  has_many :shouts,:dependent=>:destroy
  belongs_to :shout 
  

end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate!
  
  def index
    @user = current_user
    if params[:type]=="follow"
      @shouts = @user.related_shouts(false).page(params[:page]).per(10)
    elsif params[:type]=="me"
      @shouts = @user.shouts.page(params[:page]).per(10)
    else
      @shouts = Shout.top_level.page(params[:page]).per(10)
    end
  end
  
  def create

    
    shout = Shout.create(params[:shout])
    current_user.shouts <<  shout
    shout.update_attribute(:message_with_link, highlight_link(shout.message))
    redirect_to :back
  end

  def destroy
    @shout = Shout.find(params[:id])
    @shout.destroy
    redirect_to :back
  end

end

app/views/shouts/_form.html.haml
.shout
  .row
    =image_tag current_user.avatar(:small)
    =semantic_form_for Shout.new do |f|
      =f.input :message, :as=>:text, :label=>false,:hint=>"请控制字数,链接会被自动缩短。", :input_html => { :class => 'autogrow', :rows => 4, :maxlength => 340  }
      =submit_tag '发布微博',:class=>'btn'

app/views/shouts/_shout.html.haml
.shout
  .row
    .x
      =image_tag shout.user.avatar(:small)
      .shout_box
        =link_to "@"+shout.project.title, shout.project unless shout.project_id.nil?
        =link_to shout.user.name, shout.user
        =raw shout.message_with_link
        %p
          #{l(shout.created_at,:format=>:long)}
          =link_to_function "回复","$(\"##{shout.id}\").toggle()"
          =link_to "删除",shout_path(shout),:method=>:delete if current_user==shout.user

  %div{:class=>'row hidden',:id=>"#{shout.id}"}
    .x
      =image_tag current_user.avatar(:small)
      =form_for Shout.new do |f|
        =f.hidden_field :shout_id,:value=>shout.id
        =f.text_area :message,:rows=>2
        =submit_tag "发布回复",:class=>"btn margin0"

  -shout.shouts.asc(:created_at).each do |reply|

    .row
      .x
        .reply
          =image_tag reply.user.avatar(:small)
          .shout_box
            =link_to reply.user.name, reply.user
            =raw reply.message_with_link
            %p
              #{l(reply.created_at,:format=>:long)}
              =link_to "删除",shout_path(reply),:method=>:delete if current_user==reply.user

app/views/shouts/index.html.haml
%ul{:class=>"tabs",:"data-tabs"=>"tabs"}

  %li{:class=>"#{params[:type]==nil ? 'active':''}"}=link_to "大家正在说", myshouts_path
  %li{:class=>"#{params[:type]=="follow" ? 'active':''}"}=link_to "我的关注", myshouts_path("follow")
  %li{:class=>"#{params[:type]=="me" ? 'active':''}"}=link_to "我的发言", myshouts_path("me")
     


.row
  .span11=render 'form'
.row
  .span11=render @shouts

.row
  .span10.offset1= paginate @shouts