config/routes.rb
Talent::Application.routes.draw do

  get "orders/index"

  get "orders/show"

  get "orders/create"

  get "orders/edit"

  get "orders/update"

  get "orders/destroy"

  resources :artworks
  resources :sellables
  match 'artworks/by/:artist_id' => "artworks#index", as: "artist_artworks"
  match 'artworks/by/:artist_id/edit' => "artworks#edit_all", as: "edit_artist_artworks"
  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :parks

  resources :projects, :only=>[:index, :show, :new,:create, :edit,:update, :destroy]
  match 'project/:id/apply'=>"projects#apply", :as=>'project_apply'
  match 'project_membership/:id/approve'=>"projects#approve",:as=>'project_approve'
  match 'project_membership/:id/decline'=>"projects#decline",:as=>'project_decline'
  match 'project_membership/:id/quit'=>"projects#quit", :as=>'project_quit'
  match 'project/overview'=>'projects#overview', :as=>'project_overview'
  match 'project/search'=>'projects#search', :via=>[:post,:put],:as=>"project_search"
  get "project/search(/:search_id)"=>'projects#index', :as=>"projects_list"

  resources :job_posts
  match "job_posts/:id/match"=>"job_posts#matching_talent",:as=>'job_post_matching_talent'
  resources :organization_profiles

  resources :tech_posts
  match 'tech_searches/default'=>'tech_searches#show',:as=>'default_tech_post'
  resources :tech_searches


  devise_for :users, :controllers => {:registrations => "registrations", :invitations => 'invitations'}

  resources :users
  resources :ind_users, path: "artists"
  resources :org_users, path: "buyers"
  resources :shouts
  match 'weibo(/:type)'=>'shouts#index', :as=>'myshouts'

  post 'send_message'=>"messages#create", :as=>'send_message'
  post 'send_job_application'=>"job_applications#create", :as=>'send_job_application'
  get 'cancel_job_application/:id'=>'job_applications#destroy',:as=>"cancel_job_application"
  post 'send_tech_application'=>"tech_applications#create", :as=>'send_tech_application'
  get 'cancel_tech_application/:id'=>'tech_applications#destroy',:as=>"cancel_tech_application"

  match 'overview' => 'ind_users#overview', :as=>'ind_user_overview'
  match 'job_searches/default'=>'job_searches#show',:as=>'default_jobs'
  match 'talent_searches/default'=>'talent_searches#show',:as=>'default_talent'
  match 'company_searches/default'=>'company_searches#show',:as=>'default_companies'
  match 'park_searches/default'=>'park_searches#show', :as=>'default_parks'
  resources :job_searches
  resources :company_searches
  resources :talent_searches
  resources :park_searches
  match 'ind_users/:id/new/:info'=>'ind_users#new',:as=>'ind_user_new'
  match 'ind_users/:id/edit/:info'=>'ind_users#edit',:as=>'ind_user_edit'
  match 'ind_users/:id/profile'=>'ind_users#profile',:as=>'ind_user_profile'
  match 'ind_users/:id/weibo'=>'ind_users#shouts',:as=>'ind_user_shouts'


  match 'bookmarked/ind/users'=>'ind_users#bookmarked_users', :as=>"bookmarked_users"
  match 'bookmarked/org/users'=>'org_users#bookmarked_users', :as=>"bookmarked_users_for_companies"
  match 'bookmarked/companies'=>'ind_users#bookmarked_companies', :as=>"bookmarked_companies"
  match 'bookmarked/jobs'=>'ind_users#bookmarked_jobs', :as=>"bookmarked_jobs"
  match 'bookmarked/projects'=>'ind_users#bookmarked_projects', :as=>"bookmarked_projects"


  match 'org_users/:id/new/:info'=>'org_users#new',:as=>'org_user_new'
  match 'org_users/:id/edit/:info'=>'org_users#edit',:as=>'org_user_edit'
  match 'org_users/:id/profile'=>'org_users#profile',:as=>'org_user_profile'
  match 'org_users/:id/weibo'=>'org_users#shouts',:as=>'org_user_shouts'
  match 'projects/:id/weibo'=>'projects#shouts',:as=>'project_shouts'

  match 'users/:id/update/account'=>"users#update_email_or_password",:as=>'user_update_email_or_password'
  match 'users/:id/new/:info'=>'users#new',:as=>'user_new'
  match 'users/:id/edit/:info'=>'users#edit',:as=>'user_edit'
  match 'users/:id/profile'=>'users#profile',:as=>'user_profile'

  match 'org_users/:id/jobs_posts'=>'org_users#job_posts',:as=>'org_user_job_posts'
  match 'ind_users/:id/jobs_posts'=>'ind_users#job_posts',:as=>'ind_user_job_posts'

  match 'skills/list'=>'skills#list',:as=>'skills_list'

  match 'bookmark/:type/:id'=>'bookmarks#bookmark', :as=>'toggle_bookmark'

  get "referralbonus" => 'pages#referralbonus', as: "pages_referralbonus"
  get "company" => 'pages#company'
  get "services" => 'pages#services'
  get "team" => 'pages#team'
  get "contact" => 'pages#contact'
  get "jobs" => 'pages#jobs'


  root :to => 'artworks#index'

  match 'job_posts/:id/toggle_promo'=>"job_posts#toggle_promo", as: 'toggle_promo'
  match "/artists_entrance" => "artworks#index", defaults: { locale: :en }
  match "/buyer_entrance" => "artworks#index", defaults: { locale: :ch }
  resources :orders
  match "/cancel_oder/:id" => "orders#cancel", as: "cancel_order"

  namespace :admin do
    resources :artworks
    resources :orders
    resources :artists
    resources :org_users
  end

  namespace :manage do
    resources :artworks
  end

  match "artworks/page/:page" => "artworks#index"

  match "/error" => "pages#error"
  match "*path" => "artworks#index"
end

app/models/project.rb
# encoding: UTF-8
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include SimpleEnum::Mongoid

  field :title
  field :one_liner
  field :intro
  field :project_update
  field :video_code
  has_many :shouts
  has_many :photos, autosave: true, as: :attachable
  has_many :bookmarkings,:class_name=>"Bookmark", as: :bookmarkable
  has_one :download, autosave: true, as: :attachable
  has_and_belongs_to_many :project_fields
  has_and_belongs_to_many :project_needs

  field :people_count, type: Integer

  belongs_to :province
  field :province_id, type: Integer
  has_many :project_memberships
  as_enum :stage, :"概念"=>1,
                  :"开发初期"=>2,
                  :"产品原型"=>3,
                  :"市场化"=>4,
                  :"规模化"=>5
  as_enum :visibility, :"公开" =>"1", :"只给关注的人公开"=>"2", :"隐藏"=>"3"
  as_enum :has_patent, :"有"=>"1", :"无"=>"2", :"申请中"=>"3"
  scope :public, where(visibility_cd: "1")

    if Rails.env.production? || Rails.env.staging?
      has_mongoid_attached_file :logo,
        :path => ':project_logo/:id/:style.:extension',
        :default_url => '/assets/project_logo/:style/missing.jpg',
        :storage => :s3,
        :bucket => 'talent-search',
        :s3_credentials => {:access_key_id => ENV['S3_KEY'],:secret_access_key => ENV['S3_SECRET']},
        :styles => {
          :original => ['1920x1680>', :jpg],
          :small    => ['30x30#',   :jpg],
          :medium   => ['150x100',    :jpg],
          :large    => ['400x300>',   :jpg]
        }
    else
      has_mongoid_attached_file :logo,
        :default_url => '/assets/project_logo/:style/missing.jpg',
        :styles => {
          :original => ['1920x1680>', :jpg],
          :small    => ['30x30#',   :jpg],
          :medium   => ['150x100',    :jpg],
          :large    => ['400x300>',   :jpg]
        }
    end
    
  attr_accessible :title, :video_code, :download, :one_liner, :intro, :visibility, :logo, :province_id, :stage, :has_patent, :photos_attributes, :people_count, :project_need_ids, :project_field_ids
  validates :people_count, :one_liner, :visibility, :title, :intro, :province,:province_id, :stage, :presence =>true
  validates_presence_of :project_field_ids
  validates_numericality_of :people_count, :only_integer=>true, :greater_than=>0

  accepts_nested_attributes_for :photos, :allow_destroy => true
  
  def add_admin user
    membership = project_memberships.find_or_initialize_by(:user_id=>user.id)
    membership.role_cd= 1
    membership.requested_at = membership.approved_at = Time.now
    membership.save!
  end

  
  def admins
    project_memberships.where(role_cd: 1).map(&:user)
  end
  
  def all_members
    project_memberships.where(:approved_at.ne=>nil).map(&:user)
  end
  
  def pending_applications
    project_memberships.where(approved_at: nil).where(declined_at: nil)
    
  end

   
  def quit user
    project_memberships.where(:user_id=>user.id).destroy_all 
  end
  
  def new_application user
    project_memberships.create!(user_id: user.id, role_cd: 2, requested_at: Time.now)
  end
  
  def status user
    memberships = project_memberships.where(:user_id=>user.id)
    if memberships.empty?
        'new'
    elsif memberships[0].approved_at.nil? && memberships[0].declined_at.nil?
        'pending'
    elsif memberships[0].approved_at.nil? && !memberships[0].declined_at.nil?
        'declined'
    elsif memberships[0].role_cd == 2
        'member'
    else
        'admin'
    end
  end
end

app/models/project/project_field.rb
# encoding: UTF-8
class ProjectField
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include SimpleEnum::Mongoid

  
  field :name_ch
  field :name_en
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :tech_posts

 def self.populate
     ProjectField.destroy_all
     data=File.new('db/base_data/project_fields.csv').lines
       data.each_with_index do |item,index| 
         ProjectField.create(:name_ch=>item.split("//")[0].strip,:name_en=>item.split("//")[1].strip)
     end
  end

  def self.pinyin_order
    self.all.sort {|a ,b|   a.name_ch.pinyin.join <=> b.name_ch.pinyin.join }
  end
end

app/models/project/project_need.rb
# encoding: UTF-8
class ProjectNeed
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include SimpleEnum::Mongoid

  
  field :name_ch
  field :name_en
  has_and_belongs_to_many :projects

  def self.populate
    ProjectNeed.destroy_all
    self.create(:name_ch=>"投资人",:name_en=>"Investors")
    self.create(:name_ch=>"招聘人才",:name_en=>"Employees")
    self.create(:name_ch=>"合伙人",:name_en=>"Core team members")
  end
end

app/controllers/projects_controller.rb
# encoding: UTF-8
class ProjectsController < ApplicationController

  include ApplicationHelper
  before_filter :authenticate!

  def index
    if params[:search_id]
      @search = ProjectSearch.find(params[:search_id])
      @projects = Kaminari.paginate_array(@search.matching_projects).page(params[:page]).per(10)
    else
      @search = ProjectSearch.new
      @projects = Project.public.page(params[:page]).per(10)
    end
  end

  def overview
    @latest_projects = Project.limit(10)
    @latest_project_shouts = Shout.where(:project_id.in => current_user.bookmarked_ids("Project")).limit(10)
  end

  def search
    @search = ProjectSearch.create(params[:project_search])
    redirect_to projects_list_path(@search.id)
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
    @project.visibility = :"公开"
    5.times{@project.photos.build}
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      @project.add_admin current_user
      redirect_to @project
    else
      (5-@project.photos.count).times{@project.photos.build}
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    unless @project.admins.include?(current_user) || current_user.admin
      redirect_to root_url
    end
    (5-@project.photos.count).times{@project.photos.build}
  end

  def update
    @project = Project.find(params[:id])
    if !@project.admins.include?(current_user) && !current_user.admin?
      redirect_to root_url
    elsif @project.update_attributes(params[:project])
      redirect_to @project
    else
      flash[:notice]="请修改下列错误再提交"
      (5-@project.photos.count).times{@project.photos.build}
      render :edit
    end
  end

  def destroy
  end

  def apply
    @project= Project.find(params[:id])
    @project.new_application current_user
    flash[:success]="您的申请已递交，请等待项目负责人审批"
    redirect_to :back
  end
  
  def quit
    @project= Project.find(params[:id])
    @project.quit current_user
    flash[:notice]="取消申请成功"
    redirect_to :back
  end
  
  def approve
    @application = ProjectMembership.find(params[:id])  
    @application.approved_at = Time.now
    @application.save!
    redirect_to :back
  end
  
  def decline
    @application = ProjectMembership.find(params[:id])  
    @application.declined_at = Time.now
    @application.save!
    redirect_to :back
  end

  def shouts
    @project = Project.find(params[:id])
    @shouts = @project.shouts.page(params[:page]).per(10) 
  end
end

app/helpers/projects_helper.rb
#encoding: UTF-8
module ProjectsHelper
  def join_project_buttons_code project
    case project.status(current_user) 
    when "new"
      link_to "申请加入", project_apply_path(project.id),:class=>"btn primary"
    when "pending","declined"
      link_to "取消申请", project_quit_path(project.id),:class=>"btn primary"
    when "member"
      link_to "退出项目", project_quit_path(project.id),:class=>"btn primary"
    end
  end
end

app/views/projects/_admin_action.html.haml
-if @project.status(current_user) == 'admin'
  -@project.pending_applications.each do |app|
    .row
      =image_tag app.user.avatar(:small)
      =link_to app.user.name, app.user
      请求加入此项目。
    .row
      =link_to '批准', project_approve_path(app.id),:class=>'btn primary'
      =link_to '拒绝', project_decline_path(app.id),:class=>'btn primary'

app/views/projects/_project.html.haml
.job_post_snippet
  .row
    .span5
      .job_snippet_left
        .lab=link_to project.title, project
        .lab=project.province.name
    .span3
      =project.project_fields.first.name
      %br
      发布于#{time_ago_in_words(project.created_at)}以前

app/views/projects/_project_navigation.html.haml
%ul{:class=>"tabs",:"data-tabs"=>"tabs"}
  %li{class: "#{is_active? 'projects#show'}"}=link_to "项目主页", @project
  %li{class: "#{is_active? 'projects#shouts'}"}=link_to "项目微博",project_shouts_path(@project)

app/views/projects/_search_form.html.haml
=semantic_form_for @search,:url=>project_search_path do |f|
  =f.inputs do
    .row 
      .span3
        %h3 搜索选项
        =f.input :keywords
        =submit_tag "搜索",:class=>"btn"
      %h4.span3 附加选项
      .span3=f.input :project_field_id, :collection=>ProjectField.all
      .span3=f.input :stage_cd, :as=>:select, :collection=>Project.stages_for_select(:value)
      .span3=f.input :province_id, :as=>:select, :collection=> Province.all
      .span3=submit_tag "搜索",:class=>"btn"

app/views/projects/_shout.html.haml
.shout
  .row
    .span16.shout_box
      =raw shout.message_with_link
      %p
        #{link_to shout.user.name, shout.user} #{l(shout.created_at,:format=>:long)}  
        =link_to_function "回复(#{shout.shouts.count})","$(\"##{shout.id}\").toggle()"
        =link_to "删除",shout_path(shout),:method=>:delete if current_user==shout.user

  %div{:class=>'row hidden',:id=>"#{shout.id}"}
    .span16
      =form_for Shout.new do |f|
        =f.hidden_field :shout_id,:value=>shout.id
        =f.text_area :message,:rows=>2
        =submit_tag "发布回复",:class=>"btn"

      -shout.shouts.each do |reply|

        .row
          .span15.shout_box
            =raw reply.message_with_link
            %p
              #{link_to reply.user.name, shout.user} (发布于#{time_ago_in_words(reply.created_at)}以前)
              =link_to "删除",shout_path(reply),:method=>:delete if current_user==reply.user

app/views/projects/_shout_form_for_project.html.haml
.shout.row
  .span16
    =semantic_form_for Shout.new do |f|
      =f.input :project_id, :as=>:hidden, :value=>@project.id
      =f.input :message, :as=>:text, :label=>false,:hint=>"请控制字数,链接会被自动缩短。", :input_html => { :class => 'autogrow', :rows => 4, :maxlength => 340  }
      =submit_tag '发布微博',:class=>'btn'

app/views/projects/_slide_show.html.haml
#slide_show_container
  #example
    #slides
      .slides_container
        -subject.photos.each do |photo|
          =image_tag(photo.photo(:large),alt: "Slide 1", height: "300")

      /%a.prev{:href => "#"}
      /  %img{:alt => "Arrow Prev", :height => "43", :src => "/assets/img/arrow-prev.png", :width => "24"}/
      /%a.next{:href => "#"}
      /  %img{:alt => "Arrow Next", :height => "43", :src => "/assets/img/arrow-next.png", :width => "24"}/
    /%img#frame{:alt => "Example Frame", :height => "341", :src => "/assets/img/example-frame.png", :width => "739"}

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/edit.html.haml
=render 'projects/form'

app/views/projects/index.html.haml
=render 'projects/navigation'
.row
  .span3.search
    =render 'projects/search_form'
  .span13
    %h4
      -if params[:search_id].nil? 
        ="所有创业项目 (#{Project.count}个)"
          
      -else
        ="搜索结果"
        %span.view_all=link_to("浏览所有项目",projects_path)
      .add=link_to "新建项目",new_project_path
    -if @projects.empty?   
      搜索结果为0,请试试别的搜索参数！
    -else
      %table.zebra-striped
        %tr
          %th{width: "60px"} 项目Logo
          %th{width: "340px"} 项目名称
          %th{width: "100px"} 项目领域
          %th{width: "70px"} 所在地
          %th{width: "30px"} 团队
          %th{width: "30px"} 粉丝

        - for project in @projects
          %tr
            %td=image_tag project.logo(:small),height: "40px";
           
            %td
              %b=link_to project.title, project
              %p=project.one_liner
            %td
              -project.project_fields.limit(2).each do |field|
                .skill_item=field.name 
            %td=project.province.name
            %td=project.people_count 
            %td=project.bookmarkings.count
      =paginate @projects

app/views/projects/overview.html.haml
=render 'projects/navigation'

.row
  .span8
    %h4 最新项目
    =render @latest_projects
  .span8
    %h4.with_span 关注项目微博
    -if @latest_project_shouts.empty?
      %span 
        您没有关注任何项目,
        =link_to '现在就去看看吧', project_search_path
      =render Shout.where('project_id.ne'=>nil).limit(8)
    -else
      =render @latest_project_shouts

app/views/projects/shouts.html.haml
=render 'projects/project_navigation'
=render 'projects/shout_form_for_project' if current_user.projects.include?(@project)
=render @shouts
.row
  .span10= paginate @shouts

app/views/projects/show.html.haml
=render 'projects/project_navigation'
.row
  .span3
    .sidebar
      .image=image_tag @project.logo(:medium)
      = bookmark_code @project
      =join_project_buttons_code @project if current_user.is_a? IndUser
      =render 'projects/admin_action'
      =link_to "更新项目信息", edit_project_path(@project),class: 'btn primary' if @project.status(current_user)=='admin'
      =link_to "下载项目商业方案", @project.download.download.url, class: 'btn primary' unless @project.download.nil?
  .span13
    %h1.project_title=@project.title
    %p.one_liner=@project.one_liner
    %h4 项目介绍
    =@project.intro
    -unless @project.video_code.blank?
      %h4 项目视频
      =@project.video_code.html_safe
    -unless @project.photos.empty?
      %h4 项目图片
      =render 'projects/slide_show', subject: @project

    .row
      .span4
        %h4 项目所在地
        =@project.province.name
      .span3
        %h4 团队人数
        =@project.people_count
        人
      .span3
        %h4 有无专利
        =@project.has_patent
      .span3
        %h4 项目阶段
        =@project.stage
    %h4 项目领域
    -@project.project_fields.each do |field|
      .skill_item=field.name
    -unless @project.project_needs.empty?
      %h4 项目需求
      -@project.project_needs.each do |need|
        .skill_item=need.name
    -@members = @project.all_members
    %h4 项目成员(#{@members.count}人)
    %ul.horizontal
      -@members.each do |member|
        %li
          =image_tag member.avatar(:small)
          .name=link_to member.name, member
    

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>