config/routes.rb
Talent::Application.routes.draw do

  get "orders/index"

  get "orders/show"

  get "orders/create"

  get "orders/edit"

  get "orders/update"

  get "orders/destroy"

  resources :artworks
  resources :sellables
  match 'artworks/by/:artist_id' => "artworks#index", as: "artist_artworks"
  match 'artworks/by/:artist_id/edit' => "artworks#edit_all", as: "edit_artist_artworks"
  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :parks

  resources :projects, :only=>[:index, :show, :new,:create, :edit,:update, :destroy]
  match 'project/:id/apply'=>"projects#apply", :as=>'project_apply'
  match 'project_membership/:id/approve'=>"projects#approve",:as=>'project_approve'
  match 'project_membership/:id/decline'=>"projects#decline",:as=>'project_decline'
  match 'project_membership/:id/quit'=>"projects#quit", :as=>'project_quit'
  match 'project/overview'=>'projects#overview', :as=>'project_overview'
  match 'project/search'=>'projects#search', :via=>[:post,:put],:as=>"project_search"
  get "project/search(/:search_id)"=>'projects#index', :as=>"projects_list"

  resources :job_posts
  match "job_posts/:id/match"=>"job_posts#matching_talent",:as=>'job_post_matching_talent'
  resources :organization_profiles

  resources :tech_posts
  match 'tech_searches/default'=>'tech_searches#show',:as=>'default_tech_post'
  resources :tech_searches


  devise_for :users, :controllers => {:registrations => "registrations", :invitations => 'invitations'}

  resources :users
  resources :ind_users, path: "artists"
  resources :org_users, path: "buyers"
  resources :shouts
  match 'weibo(/:type)'=>'shouts#index', :as=>'myshouts'

  post 'send_message'=>"messages#create", :as=>'send_message'
  post 'send_job_application'=>"job_applications#create", :as=>'send_job_application'
  get 'cancel_job_application/:id'=>'job_applications#destroy',:as=>"cancel_job_application"
  post 'send_tech_application'=>"tech_applications#create", :as=>'send_tech_application'
  get 'cancel_tech_application/:id'=>'tech_applications#destroy',:as=>"cancel_tech_application"

  match 'overview' => 'ind_users#overview', :as=>'ind_user_overview'
  match 'job_searches/default'=>'job_searches#show',:as=>'default_jobs'
  match 'talent_searches/default'=>'talent_searches#show',:as=>'default_talent'
  match 'company_searches/default'=>'company_searches#show',:as=>'default_companies'
  match 'park_searches/default'=>'park_searches#show', :as=>'default_parks'
  resources :job_searches
  resources :company_searches
  resources :talent_searches
  resources :park_searches
  match 'ind_users/:id/new/:info'=>'ind_users#new',:as=>'ind_user_new'
  match 'ind_users/:id/edit/:info'=>'ind_users#edit',:as=>'ind_user_edit'
  match 'ind_users/:id/profile'=>'ind_users#profile',:as=>'ind_user_profile'
  match 'ind_users/:id/weibo'=>'ind_users#shouts',:as=>'ind_user_shouts'


  match 'bookmarked/ind/users'=>'ind_users#bookmarked_users', :as=>"bookmarked_users"
  match 'bookmarked/org/users'=>'org_users#bookmarked_users', :as=>"bookmarked_users_for_companies"
  match 'bookmarked/companies'=>'ind_users#bookmarked_companies', :as=>"bookmarked_companies"
  match 'bookmarked/jobs'=>'ind_users#bookmarked_jobs', :as=>"bookmarked_jobs"
  match 'bookmarked/projects'=>'ind_users#bookmarked_projects', :as=>"bookmarked_projects"


  match 'org_users/:id/new/:info'=>'org_users#new',:as=>'org_user_new'
  match 'org_users/:id/edit/:info'=>'org_users#edit',:as=>'org_user_edit'
  match 'org_users/:id/profile'=>'org_users#profile',:as=>'org_user_profile'
  match 'org_users/:id/weibo'=>'org_users#shouts',:as=>'org_user_shouts'
  match 'projects/:id/weibo'=>'projects#shouts',:as=>'project_shouts'

  match 'users/:id/update/account'=>"users#update_email_or_password",:as=>'user_update_email_or_password'
  match 'users/:id/new/:info'=>'users#new',:as=>'user_new'
  match 'users/:id/edit/:info'=>'users#edit',:as=>'user_edit'
  match 'users/:id/profile'=>'users#profile',:as=>'user_profile'

  match 'org_users/:id/jobs_posts'=>'org_users#job_posts',:as=>'org_user_job_posts'
  match 'ind_users/:id/jobs_posts'=>'ind_users#job_posts',:as=>'ind_user_job_posts'

  match 'skills/list'=>'skills#list',:as=>'skills_list'

  match 'bookmark/:type/:id'=>'bookmarks#bookmark', :as=>'toggle_bookmark'

  get "referralbonus" => 'pages#referralbonus', as: "pages_referralbonus"
  get "company" => 'pages#company'
  get "services" => 'pages#services'
  get "team" => 'pages#team'
  get "contact" => 'pages#contact'
  get "jobs" => 'pages#jobs'


  root :to => 'artworks#index'

  match 'job_posts/:id/toggle_promo'=>"job_posts#toggle_promo", as: 'toggle_promo'
  match "/artists_entrance" => "artworks#index", defaults: { locale: :en }
  match "/buyer_entrance" => "artworks#index", defaults: { locale: :ch }
  resources :orders
  match "/cancel_oder/:id" => "orders#cancel", as: "cancel_order"

  namespace :admin do
    resources :artworks
    resources :orders
    resources :artists
    resources :org_users
  end

  namespace :manage do
    resources :artworks
  end

  match "artworks/page/:page" => "artworks#index"

  match "/error" => "pages#error"
  match "*path" => "artworks#index"
end

app/models/job_post.rb
# encoding: UTF-8
class JobPost 
  include Mongoid::Document
  include Mongoid::Timestamps
  include ApplicationHelper

  default_scope all(sort: [[ :created_at, :desc ]])
  scope :current, where(:expiration.gte=>Date.today)
  scope :on_promo, where(:promo_start_date.lte=>Date.today).where(:promo_end_date.gte=>Date.today)

  has_many :bookmarkings,:class_name=>"Bookmark", as: :bookmarkable

  include SimpleEnum::Mongoid
  as_enum :job_type,    :"全职"=>"1",:"兼职"=>"2", :"短期项目"=>"3", :"实习"=>"4"
  as_enum :salary, :"面议"=>"0", :"5000元以下"=>"1", :"5000元-1万元"=>"2", :"1万元-2万元"=>"3", :"2万元-3万元"=>"4", :"3万元－5万元"=>"5", :"5万元－10万元"=>"6", :"10万元以上"=>"7"
  as_enum :years_required, :"无要求"=>"1", :"1年以上"=>"2", :"3年以上"=>"3", :"5年以上"=>"4", :"10年以上"=>"5"
  as_enum :company_type, :"国企"=>"1", :"民企"=>"2", :"外企"=>"3", :"非营利组织"=>"4", :"学术研究机构"=>"5"
  as_enum :degree_requirement, :"不限"=>"0",
                        :"专科"=>"1",
                        :"学士"=>"2",
                        :"硕士"=>"3",
                        :"博士"=>"4",
                        :"医学博士"=>"5",
                        :"法学博士"=>"6"

  field :title
  field :description
  field :job_requirement
  field :company_name
  field :expiration, type: Date
  field :contact_person
  field :email
  field :phone_number
  field :logo
  field :website
  field :is_official, type: Boolean, default: true
  field :promo_start_date, type: Date
  field :promo_end_date, type: Date

  attr_accessible :title, :city_id, :province_id, :company_type, :industry_id, 
    :years_required, :years_required_cd,
    :degree_requirement, :degree_requirement_cd,
      :company_name, :company_id, :description, :job_requirement,
      :job_type, :job_type_cd, :salary, :salary_cd, :expiration, :contact_person, 
      :phone_number, :email, :logo, :website, :user_id, :skill_ids, :is_official,
      :promo_start_date, :promo_end_date

  validates :title, :company_name, :industry_id, :company_type, :province_id, :city_id,
      :description, :job_requirement, :job_type, :degree_requirement, :years_required, :salary,
      :expiration, :email, :presence=>true
  validates :email, email: true
  belongs_to :industry
  belongs_to :province
  field :province_id, type: Integer
  belongs_to :city
  field :city_id, type: Integer
  belongs_to :user
  has_and_belongs_to_many :skills
  has_many :job_applications
#  fulltext_search_in :title, :description, :job_requirement
  
  def mcount user
    (skills.to_set & user.skills.to_set).size    
  end
  
  def mcount_percent user
    percent = mcount(user)*100/skills.count
    "#{percent}%"
  end
  
  def matches
    users = skills.map{|skill| skill.users}.flatten.uniq
    users.sort!{|a,b| a.mcount(self) <=> b.mcount(self)}
  end
  
  def related_jobs
    jobs = skills.map{|skill| skill.job_posts.current}.flatten.uniq
    jobs.sort!{|a,b| mcount(a) <=> mcount(b)}
  end
  
  

  def self.populate
    JobPost.delete_all
    data = get_csv_data 'db/base_data/job_posts.csv'

      data.each do |post|
        city = City.where(:name_ch => /#{post['city_id']}/) 
        city = City.where(:name_ch => /其他/) if city.empty?
        post["job_type_cd"]=post["job_type_cd"].to_i
        post["industry_id"]=post["industry_id"].to_i
        puts city[0].name
        puts post
        JobPost.create(post.merge({"city_id"=>city[0].id })
        )
      end
  end

  def on_promo?
    promo_start_date != nil and
    promo_end_date != nil and
    promo_start_date <= Date.today and
    promo_end_date >=Date.today
  end

end

app/controllers/job_posts_controller.rb
# encoding: UTF-8
class JobPostsController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate!
  def index
    @user = current_user
    @job_posts = JobPost.all
  end

  def show
    @job_application = JobApplication.new
    @job_post = JobPost.find(params[:id])
    @same_industry_jobs = JobPost.current.where(:industry_id=>@job_post.industry_id).limit(6) - @job_post.to_a
    @same_company_jobs = JobPost.current.where(:user_id=>@job_post.user_id).limit(6)-@job_post.to_a
    @related_skill_jobs = @job_post.related_jobs[0..5]-@job_post.to_a
    @latest_jobs = JobPost.current.limit(5)
  end

  def new
    @user = current_user
    @job_post = JobPost.new
    @job_post.expiration = Date.today + 1.month
    if (profile = current_user.org_profile)
      @job_post.company_name = current_user.org_profile.company_name
      @job_post.industry_id=current_user.org_profile.industry_id
      @job_post.company_type=current_user.org_profile.company_type
      @job_post.contact_person = profile.contact_person
      @job_post.phone_number = profile.phone_number
      @job_post.email = profile.email
    end
  end

  def create
    @user = current_user
    @job_post = current_user.job_posts.new(params[:job_post])
    @job_post.is_official = current_user.is_a?(OrgUser)
    if @job_post.save
      update_skills(@job_post, params)
      current_user.job_posts << @job_post
      redirect_to @job_post, :notice => "成功新建职位。"
    else
      render :action => 'new'
    end
  end

  def edit
    @job_post = JobPost.find(params[:id])
    authorize! :manage, @job_post
  end

  def update
    @job_post = JobPost.find(params[:id])
    authorize! :manage, @job_post
    if @job_post.update_attributes(params[:job_post])
      update_skills(@job_post, params)
      redirect_to @job_post, :notice  => "成功更新职位。"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @job_post = JobPost.find(params[:id])
    authorize! :manage, @job_post
    @job_post.destroy
    redirect_to org_user_job_posts_url(current_user), :notice => "成功删除职位"
  end
  
  def matching_talent
    @job_post = JobPost.find(params[:id])
    @users = @job_post.matches
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(10)
  end
  
  def toggle_promo
    @job_post = JobPost.find(params[:id])
    if can? :manage, :job_posts
      if @job_post.promo_start_date.nil?
        today = Date.today
        @job_post.promo_start_date = Date.new(today.year, today.month, 1)
        @job_post.promo_end_date = Date.new(today.year, today.month + 1, 1) - 1
        @job_post.save!
      else
        @job_post.promo_start_date = nil
        @job_post.promo_end_date = nil
        @job_post.save!
      end
    end
    redirect_to :back
  end
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/_apply_box.html.haml
#modal-from-dom.modal.hide.fade
  .modal-header
    =link_to "&times;".html_safe,'#',:class=>'close'
    %h3 发送申请
  
  =semantic_form_for @job_application,:url=>send_job_application_path do |f| 
    .modal-body          
      =f.input :job_post_id, :as=>:hidden, :value=>@job_post.id
      =f.input :content, :as=>:text, :hint=>"选填。突出自己的强处，为自己加分。" ,:input_html => { :class => 'autogrow', :rows => 15}
    .modal-footer
      =submit_tag "申请",:class=>'btn'

app/views/job_posts/_form.html.haml
= semantic_form_for @job_post do |f|

  = f.inputs do
    .row
      .span8=f.input :company_name
      .span3=f.input :industry_id,:as=>:select, :collection=>Industry.all.pinyin_order.map{|x| [t(x.name), x.id]},:prompt => t("Select one")
      .span2=f.input :company_type, :as=>:select, :collection=>JobPost.company_types_for_select,:prompt => t("Select one")
    .row
      .span5=f.input :title
      .span2=f.input :job_type, :as=>:select, :collection=>JobPost.job_types_for_select,:prompt => t("Select one")
      .span2=f.input :salary, :as=>:select, :collection=>JobPost.salaries_for_select,:prompt => t("Select one")
      =render 'shared/city_picker',:f=>f,:city_id=>@job_post.city_id
    .row
      .span3=f.input :degree_requirement, :as=>:select, :collection=>JobPost.degree_requirements_for_select, :prompt=>t("Select one")
      .span2=f.input :years_required, :as=>:select, :collection=>JobPost.years_requireds_for_select,:prompt => t("Select one")
      .span4
        =f.label "推广开始日期"
        =f.date_select :promo_start_date, {prompt: {day: t("Select one"), month: t("Select one"), year: t("Select one")}},{class: "date"}
      .span4
        =f.label "推广结束日期"
        =f.date_select :promo_end_date, {prompt: {day: t("Select one"), month: t("Select one"), year: t("Select one")}},{class: "date"}
    .row
      .span13
        .tiny=f.input :description,:as=>:text,:input_html => { :class => 'autogrow', :rows => 10}
    .row
      .span13
        .tiny=f.input :job_requirement,:as=>:text,:rows=>10,:input_html => { :class => 'autogrow', :rows => 10}
    .row
      .span2=f.input :contact_person
      .span3=f.input :phone_number
      .span4=f.input :email
      .span4
        =f.label :expiration
        =f.date_select :expiration,{},{:class=>"date"}
   
    /.row
    /  .span13
    /    =f.input :website,:input_html => { :placeholder => 'http://www.example.com'}
    =render 'shared/skill_picker',:item=>@job_post

    = f.action :submit, :button_html => { :class=>"btn primary"}
 

app/views/job_posts/_formtest.html.haml
=form_for @job_post do |f|
  =select_tag "province", options_from_collection_for_select(Province.all, "id", "name")
  =select_tag "city",[]
  
:javascript

  $(document).ready(function() {
    initDynamicOptionLists();
  });

  var names = new DynamicOptionList();
  names.addDependentFields("province","city");
  names.forValue(1).addOptionsTextValue("真人",1);
 
  names.forValue(2).addOptionsTextValue("作战",1);

app/views/job_posts/_job_post.html.haml
.job_post_snippet
  .row
    .span5
      .job_snippet_left
        .lab=link_to job_post.company_name,job_post.user if job_post.user.is_a? OrgUser
        .lab=job_post.company_name unless job_post.user.is_a? OrgUser
        .lab=link_to job_post.title ,job_post

app/views/job_posts/edit.html.haml
- title "Edit Job Post"
= render 'form'

app/views/job_posts/index.html.haml
=render 'ind_users/navigation'
- title "Job Posts"
%table.zebra-striped
  %tr
    %th 公司/机构
    %th 职位
    %th 月薪
    %th 地点
    %th 截止日期
    %th
    %th
  - for job_post in @job_posts
    %tr
      %td= job_post.company_name 
      %td=link_to job_post.title,job_post
      %td= job_post.salary ||'面议'
      %td= job_post.city.name
      %td= l job_post.expiration,:format=>:long unless job_post.expiration.nil?
      %td= link_to "收藏", job_post
      %td= link_to "查看", edit_job_post_path(job_post)

app/views/job_posts/matching_talent.html.haml
%h3 技能匹配人才
%h4
  匹配职位：
  =link_to @job_post.title, @job_post   
=link_to "返回职位列表", org_user_job_posts_path(@job_post.user) if current_user.is_a? OrgUser
=link_to "返回职位列表", ind_user_job_posts_path(@job_post.user) if current_user.is_a? IndUser
-if @users.empty?   
  暂时没有匹配人才。
  =link_to '多加些职位关键词吧！',edit_job_post_path(@job_post)
-else    
  %table.zebra-striped
    %tr
      %th{width:200} 名字 
      %th{width:500} 最近工作/学历
      %th{width:100} 匹配指数  
      %th{width:100} 被关注
      %th{width:100}
    - for user in @users
      
      %tr{:id=>"#{user.id}"}
        %td
          .left= image_tag user.avatar(:small)
          .left
            %b= link_to user.profile.name, user
            %p="#{user.profile.province.name}, #{user.profile.province.country.name}"
        %td    
          -if !user.experiences.empty?
            -ex = user.experiences[0]
            %p
              ="#{ex.job_title},#{ex.company_name}"
              ="(#{l(ex.start_date,format: :short2)}-#{ex.end_date.nil? ? "至今" : l(ex.end_date,format: :short2)})"
          -if !user.educations.empty?
            -ed = user.educations[0]
            %p
              ="#{ed.program} #{ed.degree_type},#{ed.school}"
              ="(#{l(ed.start_date,format: :short2)}-#{ed.end_date.nil? ? "至今" : l(ed.end_date,format: :short2)})"
        %td= @job_post.mcount_percent(user)
        %td= user.bookmarkings.count

        %td= bookmark_code(user)
        
.row
  .span10= paginate @users

app/views/job_posts/new.html.haml
= # coding: UTF-8 

=render "#{current_user.class.to_s.pluralize.underscore}/navigation"
%h3 发布新职位
-if current_user.is_a? IndUser
  注意:如需以个人名义发布职位,您必须得到此公司的授权,发布信息必须为真实信息。虚假信息将被删除。
= render 'form'

app/views/job_posts/show.html.haml
.row
  .span11
    .row
      .span5
        %h4 公司名称
        =@job_post.user.is_a?(OrgUser) ? link_to(@job_post.company_name,@job_post.user) : @job_post.company_name
      .span2
        %h4 行业
        =@job_post.industry.name 
      .span2
        %h4 公司性质
        =@job_post.company_type
      .span2
        %h4 工作地点
        =@job_post.province.name
        =@job_post.city.name
    .row
      .span3 
        %h4 职位名称
        =@job_post.title
      .span2
        %h4 工作性质
        =@job_post.job_type
      .span2
        %h4 经验要求
        =@job_post.years_required
      .span2
        %h4 学历要求
        =@job_post.degree_requirement
      .span2
        %h4 月薪
        =@job_post.salary

    .row
      .span11
        %h4 职位描述
        .description=raw @job_post.description
    .row
      .span11 
        %h4 用人要求:
        .description=raw @job_post.job_requirement
    -if false
      .row
        .span2
          %h4 联系人
          =(person=@job_post.contact_person).blank? ? '未填' : person 
        .span3
          %h4 电话号码:
          =(no=@job_post.phone_number).blank? ? '未填' : no
        .span3
          %h4 电子邮件:
          =(email=@job_post.email).blank? ? '未填' : mail_to(email)
        .span3
          %h4 截止日期:
          =l @job_post.expiration, :format=>:long
    /.row
    /  .span11
    /    %h4 职位申请链接:
    /    =(url=@job_post.website).blank? ? '未填' : link_to(url, url)
    .row
      .span11
        %h4 相关技能:
        -if (skills=@job_post.skills).blank?
          未填
        -else
          %p=render(skills)

  .span5
    .sidebar
      %br
      .image
        -if @job_post.user.is_a?(OrgUser)
          =image_tag @job_post.user.avatar.url(:medium)
        -else
          =image_tag 'logo/medium/missing.jpg'
      -if @job_post.on_promo?
        %p.one_liner
          ="千元奖金推荐职位"
          =link_to "详情", pages_referralbonus_path
      -if current_user.admin?
        -if @job_post.promo_start_date.nil?
          =link_to "设本月奖",toggle_promo_path(@job_post), class: "btn primary"
        -else
          =link_to "取消奖金",toggle_promo_path(@job_post), class: "btn primary"
      =render 'pages/invitation_message_box'
      =link_to "推荐给朋友","",:'data-controls-modal'=>"modal-from-dom",:'data-backdrop'=>"true", :class=>'btn primary'

      -if current_user.is_a?(IndUser) && current_user!=@job_post.user
        =render 'job_posts/apply_box'
        -if !current_user.job_applied?(@job_post)
          =link_to "申请职位","",:'data-controls-modal'=>"modal-from-dom",:'data-backdrop'=>"true", :class=>'btn primary'
        -else 
          =link_to "撤销申请", cancel_job_application_path(current_user.get_job_application(@job_post)), :class=>"btn primary"
        =bookmark_code(@job_post)
      -if current_user == @job_post.user
        =link_to "所有发布",send("#{current_user.class.to_s.underscore}_job_posts_path", current_user.id),:class=>'btn'
        =link_to "添加",new_job_post_path,:class=>'btn' 
        = link_to "编辑", edit_job_post_path(@job_post) ,:class=>'btn' 
        =link_to "删除", @job_post, :confirm => '确认删除吗?', :method => :delete ,:class=>'btn' 
    -if current_user != @job_post.user
      -unless @latest_jobs.blank?
        .module
          %h4 悟空最新职位
          .list=render @latest_jobs
      -unless @same_company_jobs.blank?
        .module
          %h4 同一来源职位
          .list=render @same_company_jobs
      -unless @related_skill_jobs.blank?
        .module
          %h4 相关技能职位
          .list=render @related_skill_jobs  
      -unless @same_industry_jobs.blank?
        .module
          %h4 同一行业职位
          .list=render @same_industry_jobs  